name: drupal-boilerplate

recipe: drupal10

config:
  php: 8.1
  composer_version: 2.5.1
  database: mariadb:custom
  via: nginx
  webroot: web
  build:
    - composer install --profile

proxy:
  node:
    - "node.drupal-boilerplate.lndo.site:3000"

services:
  # Use official mariadb for arm64 speed/support.
  # https://github.com/bitnami/charts/issues/7305
  database:
    app_mount: false
    overrides:
      image: mariadb:10.6
      command: docker-entrypoint.sh mariadbd
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  mailhog:
    type: mailhog
    app_mount: false
    portforward: true
    hogfrom:
      - appserver

  node:
    type: node:custom
    ssl: true
    sslExpose: false
    scanner: false
    port: 3000
    overrides:
      image: node:18

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.
    cmd: /usr/local/bin/npm

  theme:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
    cmd: /usr/local/bin/npm

events:
  post-start:
    - appserver: >
        if ! drush status --fields=bootstrap | grep -qi "successful"; then
          sleep 10
          drush si --existing-config --account-name=admin --account-pass=password -y
          drush cr
          drush uli
        fi
