name: drupal-boilerplate

recipe: drupal10

config:
  php: 8.1
  composer_version: 2.5.1
  database: mariadb:custom
  via: nginx
  webroot: web
  build:
    - composer install --profile

proxy:
  node:
    # This will need to be changed if you want to use HMR for Vite
    # drupal-boilerplate should be changed to whatever "name:" is.
    - "node.drupal-boilerplate.lndo.site:3000"

tooling:
  drush:
    cmd: /bin/sh -c "drush --root=$LANDO_WEBROOT --uri=https://$LANDO_APP_NAME.lndo.site $@" "$0"

  npm:
    service: node
    description: Run NPM commands within the node service.

  theme:
    service: node
    description: Run NPM commands for the theme.
    dir: /app/web/themes/contrib/dvb
    cmd: npm

services:
  # Optionally force the app into production mode.
  # appserver:
  #   overrides:
  #     environment:
  #       ENVIRONMENT_TYPE: production

  database:
    # Use official mariadb for arm64 speed/support.
    # https://github.com/bitnami/charts/issues/7305
    # https://github.com/lando/lando/issues/2688
    app_mount: false
    type: compose
    volumes:
      mariadb: {}
    services:
      image: mariadb:10.6
      command: docker-entrypoint.sh mariadbd
      environment:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        MARIADB_DATABASE: drupal10
        MARIADB_USER: drupal10
        MARIADB_PASSWORD: drupal10
      volumes:
        - mariadb:/var/lib/mysql

  mailhog:
    # Mailhot is a test service for email.
    type: mailhog
    app_mount: false
    portforward: true
    hogfrom:
      - appserver

  node:
    # Package up node for development of themes and testing.
    # Currently Lando does not support Node 18 built-in.
    type: node:custom
    ssl: true
    sslExpose: false
    port: 3000
    overrides:
      image: node:18-alpine

events:
  post-start:
    # Wait for database then install Drupal from config.
    - appserver: >
        until drush sql:query ';'>/dev/null 2>&1; do
          echo "Waiting for database..."; sleep 1;
        done

        if ! drush status --field=bootstrap | grep -qi "successful"; then
          drush si --existing-config --account-name=admin -y;
        fi
