name: Lando Start

on:
  release:
    types: [created]
  push:
    branches: [main]

jobs:
  lando-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-versions:
          - edge
        os:
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Grab latest edge Lando CLI
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
          sudo chmod +x /usr/local/bin/lando
      - name: Setup Lando cache
        uses: actions/cache@v2
        with:
          path: ~/.lando/cache
          key: ${{ runner.os }}-lando-${{ matrix.lando.versions }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-lando-${{ matrix.lando.versions }}-
      - name: Start Lando
        run: lando start
